# Generated by Django 4.2.9 on 2024-12-31 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gtd_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='retrospective',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='retrospective',
            name='sprint_end',
        ),
        migrations.RemoveField(
            model_name='retrospective',
            name='sprint_start',
        ),
        migrations.AddIndex(
            model_name='inboxitem',
            index=models.Index(fields=['user', 'processed', 'eliminated'], name='gtd_app_inb_user_id_b01bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='inboxitem',
            index=models.Index(fields=['created_at'], name='gtd_app_inb_created_f32a26_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['deadline'], name='gtd_app_pro_deadlin_b5db83_idx'),
        ),
        migrations.AddIndex(
            model_name='retrospective',
            index=models.Index(fields=['user', 'created_at'], name='gtd_app_ret_user_id_6a4e65_idx'),
        ),
        migrations.AddIndex(
            model_name='singletask',
            index=models.Index(fields=['user', 'is_completed', 'is_in_sprint'], name='gtd_app_sin_user_id_0feaad_idx'),
        ),
        migrations.AddIndex(
            model_name='singletask',
            index=models.Index(fields=['sprint_status'], name='gtd_app_sin_sprint__1a7c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='singletask',
            index=models.Index(fields=['category'], name='gtd_app_sin_categor_0769de_idx'),
        ),
        migrations.AddIndex(
            model_name='singletask',
            index=models.Index(fields=['completed_at'], name='gtd_app_sin_complet_13cc59_idx'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtd_app.sprint'),
        ),
        migrations.AddField(
            model_name='retrospective',
            name='sprint',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gtd_app.sprint'),
        ),
        migrations.AddField(
            model_name='singletask',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtd_app.sprint'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['user', 'is_active'], name='gtd_app_spr_user_id_ebc312_idx'),
        ),
    ]
