# Generated by Django 4.2.9 on 2024-12-31 16:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gtd_app', '0002_sprint_alter_retrospective_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cost', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('benefit', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('estimated_time', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_in_sprint', models.BooleanField(default=False)),
                ('sprint_status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='benefit',
        ),
        migrations.RemoveField(
            model_name='project',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='project',
            name='estimated_time',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_in_sprint',
        ),
        migrations.RemoveField(
            model_name='project',
            name='parent_project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sprint',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sprint_status',
        ),
        migrations.AddField(
            model_name='sprint',
            name='duration_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'is_completed'], name='gtd_app_pro_user_id_993d83_idx'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='gtd_app.project'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtd_app.sprint'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['project'], name='gtd_app_pro_project_ae82ca_idx'),
        ),
    ]
