# Generated by Django 4.2.9 on 2024-12-31 16:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtd_app', '0003_projecttask_remove_project_benefit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='benefit',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='project',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cost',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='is_in_sprint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtd_app.sprint'),
        ),
        migrations.AddField(
            model_name='project',
            name='sprint_status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
