# Generated by Django 4.2.9 on 2025-01-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtd_app', '0004_project_benefit_project_completed_at_project_cost_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inboxitem',
            name='gtd_app_inb_user_id_b01bc4_idx',
        ),
        migrations.RemoveIndex(
            model_name='inboxitem',
            name='gtd_app_inb_created_f32a26_idx',
        ),
        migrations.RemoveIndex(
            model_name='sprint',
            name='gtd_app_spr_user_id_ebc312_idx',
        ),
        migrations.AddField(
            model_name='inboxitem',
            name='archive_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inboxitem',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
