# Generated by Django 4.2.9 on 2025-01-02 17:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gtd_app', '0005_remove_inboxitem_gtd_app_inb_user_id_b01bc4_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='gtd_app_pro_deadlin_b5db83_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='gtd_app_pro_user_id_993d83_idx',
        ),
        migrations.RemoveIndex(
            model_name='projecttask',
            name='gtd_app_pro_project_ae82ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='retrospective',
            name='gtd_app_ret_user_id_6a4e65_idx',
        ),
        migrations.RemoveIndex(
            model_name='singletask',
            name='gtd_app_sin_user_id_0feaad_idx',
        ),
        migrations.RemoveIndex(
            model_name='singletask',
            name='gtd_app_sin_sprint__1a7c4d_idx',
        ),
        migrations.RemoveIndex(
            model_name='singletask',
            name='gtd_app_sin_categor_0769de_idx',
        ),
        migrations.RemoveIndex(
            model_name='singletask',
            name='gtd_app_sin_complet_13cc59_idx',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='is_completed',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='completed_at',
            new_name='archived_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='sprint_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='projecttask',
            old_name='is_completed',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='projecttask',
            old_name='completed_at',
            new_name='archived_date',
        ),
        migrations.RenameField(
            model_name='projecttask',
            old_name='sprint_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='singletask',
            old_name='is_completed',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='singletask',
            old_name='completed_at',
            new_name='archived_date',
        ),
        migrations.RenameField(
            model_name='singletask',
            old_name='sprint_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_in_sprint',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='is_in_sprint',
        ),
        migrations.RemoveField(
            model_name='retrospective',
            name='user',
        ),
        migrations.RemoveField(
            model_name='singletask',
            name='is_in_sprint',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='is_active',
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='retrospective',
            name='average_efficiency',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='retrospective',
            name='completed_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='retrospective',
            name='completion_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='retrospective',
            name='total_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='singletask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='benefit',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_time',
            field=models.FloatField(default=1.0, help_text='Estimated time in weeks (0 for less than a week)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='benefit',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='cost',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='estimated_time',
            field=models.FloatField(default=1.0, help_text='Estimated time in weeks (0 for less than a week)'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='retrospective',
            name='sprint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gtd_app.sprint'),
        ),
        migrations.AlterField(
            model_name='singletask',
            name='benefit',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='singletask',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='singletask',
            name='cost',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='singletask',
            name='estimated_time',
            field=models.FloatField(default=1.0, help_text='Estimated time in weeks (0 for less than a week)'),
        ),
        migrations.AlterField(
            model_name='singletask',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
